
version: '2.1'
services: 
  live-reload:
    image: audio-studio
    build: .
    environment:
      PORT: 3333
    command: 
      - npm
      - run
      - live-reload
    volumes:
      - .:/audio-studio
      - node_modules:/audio-studio/node_modules
    ports:
      - 3333:3333
volumes:
  node_modules: {}